CREATE INDEX products_active_category_idx ON products (category_id, added_at DESC) WHERE is_active;
CREATE INDEX products_active_brand_idx ON products (brand_id, added_at DESC) WHERE is_active;
CREATE INDEX products_active_subcategory_idx ON products (category_id, subcategory) WHERE is_active;
CREATE INDEX products_purchasable_idx ON products (category_id, brand_id, price) WHERE is_active AND stock > 0;
CREATE INDEX products_specs_gin_idx ON products USING gin (specs);
CREATE INDEX product_images_product_position_idx ON product_images (product_id, position);
CREATE UNIQUE INDEX product_images_one_primary_per_product_idx ON product_images (product_id) WHERE is_primary;
CREATE INDEX product_variation_items_variation_position_idx ON product_variation_items (variation_id, position);
CREATE INDEX product_variation_items_product_idx ON product_variation_items (product_id);
CREATE INDEX offers_active_dates_idx ON offers (status, starts_at, ends_at);
CREATE INDEX offer_products_product_idx ON offer_products (product_id);
CREATE INDEX addresses_user_idx ON addresses (user_id);
CREATE UNIQUE INDEX addresses_default_per_user_idx ON addresses (user_id) WHERE is_default;
CREATE INDEX cart_items_user_idx ON cart_items (user_id);
CREATE INDEX cart_items_product_idx ON cart_items (product_id);
CREATE INDEX wishlist_items_user_idx ON wishlist_items (user_id);
CREATE INDEX wishlist_items_product_idx ON wishlist_items (product_id);
CREATE INDEX orders_user_placed_idx ON orders (user_id, placed_at DESC);
CREATE INDEX order_items_order_idx ON order_items (order_id);
CREATE INDEX order_items_product_idx ON order_items (product_id) WHERE product_id IS NOT NULL;
CREATE INDEX order_events_order_created_idx ON order_events (order_id, created_at);
CREATE INDEX product_reviews_product_created_idx ON product_reviews (product_id, created_at DESC);
CREATE INDEX product_reviews_user_product_idx ON product_reviews (user_id, product_id);
CREATE UNIQUE INDEX signup_authorizations_unconsumed_token_idx ON signup_authorizations (token_hash) WHERE consumed_at IS NULL;
CREATE INDEX signup_authorizations_token_email_idx ON signup_authorizations (token_hash, email_hash);
CREATE INDEX signup_authorizations_expiry_idx ON signup_authorizations (expires_at);
CREATE INDEX worker_rate_limits_lookup_idx ON worker_rate_limits (action, dimension, subject_hash, created_at DESC);
